spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG